# Generated by Django 4.2.29 on 2026-04-04 09:23

from django.db import migrations, models


def seed_initial_stock(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(stock=0).update(stock=10)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Units available. 0 = out of stock.'),
        ),
        migrations.RunPython(seed_initial_stock, migrations.RunPython.noop),
    ]
